<Adm>:
    TelaDeRegistro:
        id: registro
        name: 'registro'

<TelaDeRegistro>:
    GridLayout:
        cols: 1
        spacing: [6]

        Button:
            text: 'BRINQUEDOS'
            on_press: print("ouch! More gently please")
            on_release: print("ahhh")
        Button:
            text: 'COMIDAS'
        Button:
            text: 'ANIMAIS'
        Button:
            text: 'JOGOS'


# Telas
